### ISSUE TITLE
Implement other crop types

### ISSUE THREAD

**Issue by andy-williams** [andy-williams/Magick.NET.WebImageExtensions#1]
Right now, only `CropType.Center` is supported.

https://github.com/andy-williams/Magick.NET.WebImageExtensions/blob/master/Magick.NET.WebImageExtensions/MagickImageWebImageResizerExtensions.cs#L48

**Comment by hawthord** [comment]
Hi Andy! I have created an implementation for CropType.TopLeft I'd like to submit.

**Comment by andy-williams** [comment]
Didn't really expect anyone to pick this up, being completely new and all, so this is awesome !! 👍  send a PR through and let's have a look.

**Comment by hawthord** [comment]
Thanks! I've submitted PR [https://github.com/andy-williams/Magick.NET.WebImageExtensions/pull/4](https://github.com/andy-williams/Magick.NET.WebImageExtensions/pull/4) . CropType.TopLeft was simplest, since it's based out of the top left corner. If I can figure out the coordinates for the bottom right corner, the top right and bottom left will follow easily.

**Comment by hawthord** [comment]
I just submitted PR #5 with all other crop types.

**Comment by andy-williams** [comment]
Awesome !!!! Thanks :) All merged 👍
